### ISSUE TITLE
About Sample template

### ISSUE THREAD

**Issue by CMingTseng** [cnrture/QuickProjectWizard#15]
Dear Sir

Sample template suggestions for issue - 4

(https://github.com/cnrture/QuickProjectWizard/issues/4#issuecomment-2329687901)

Is it possible to use your project https://github.com/cnrture/HarryPotter-ComposeMultiplatform

As a base template?

In addition, can the ktor part be switched to ktorfit (https://foso.github.io/Ktorfit/)? Developers who have used Retrofit in the past can quickly get started.

And HarryPotter-ComposeMultiplatform also contains a good nav package (voyager)

Perhaps you can also add precompose

This allows developers to share viewmodels in compose and xml

THX

**Comment by cnrture** [comment]
Hi, I'm currently working on a CMP template, but it won't include Voyager or Precompose. It will be with Android ViewModel and Navigation structure as in this project: https://github.com/cnrture/Valorant-App-Compose-Multiplatform. Because both of them have support now.

**Comment by CMingTseng** [comment]
> Hi, I'm currently working on a CMP template, but it won't include Voyager or Precompose. It will be with Android ViewModel and Navigation structure as in this project: https://github.com/cnrture/Valorant-App-Compose-Multiplatform. Because both of them have support now. I will also look into Ktorfit, thanks 🙏

Hello

Good to hear about the CMP template part

I went to see the project you mentioned Valorant-App-Compose-Multiplatform(

https://github.com/cnrture/Valorant-App-Compose-Multiplatform)

There are a few problems I encountered before

I don’t know if you have encountered it there

See BuildKonfig(https://github.com/yshrsmz/BuildKonfig)

I myself encountered the problem of using

buildConfigField(Type.BOOLEAN, "DEBUG", false.toString())

Will cause iOS with cocoapods compilation to fail

Then

Compose-Multiplatform-Wizard part of terrakok
It is recommended instead
gmazzo's gradle-buildconfig-plugin(
https://github.com/gmazzo/gradle-buildconfig-plugin)

Then for the Navigation part, you use jetbrains' navigation (modified from AndroidX Jetpack)

I may not be able to use this lib very well.

Because I just "added" to the common section
not actually used
Just let my test project "unusable" in the desktop section

Display on macOS

"WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES"


Show on Windows
"Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt"

I don’t know if you have encountered


Thanks
