### ISSUE TITLE
can supoort Full-Multiplatform-Compose ?

### ISSUE THREAD

**Issue by CMingTseng** [cnrture/QuickProjectWizard#4]
Dear Sir

Thx your plugin

can ref this : https://github.com/jakepurple13/Full-Multiplatform-Compose-Plugin 

  supoort Full-Multiplatform-Compose  ?  use  ktor /koin /.....
  
 and  use  gradle over 8.x.x   &  new IDEA version ?
 
 THX

**Comment by cnrture** [comment]
Hi ✌️ thank you for your advice. Added to my notes. I plan to support as soon as possible 🙏

**Comment by CMingTseng** [comment]
> Hi ✌️ thank you for your advice. Added to my notes. I plan to support as soon as possible 🙏

Thank you for your willingness to develop

I have another suggestion about ktor

Because there is currently a Retrofit option when the plugin is created.

In the ktor part, I suggest that you can add reference to Retrofit and then modify Ktorfit.


https://foso.github.io/Ktorfit/installation/

Then kotlin 2.0.0 started to support composeResources in the KMP+CMP part.

https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

I suggest that this part can imitate the drawable part of Android’s past templates and place the app icon (or the icon of your plugin)


Use Napier in LOG section

https://github.com/AAkira/Napier


ps. After studying your plugin, I found that it can be added in the Android section.
(I couldn’t find a way before)
(Full-Multiplatform-Compose-Plugin is added in the Extras section)

Anyway, thank you for the plugin
